### ISSUE TITLE
Publish Releases and Integrate with NetData Installer

### ISSUE THREAD

**Issue by prologic** [netdata/kernel-collector#11]
As discussed; we will not worry about x86/i386 support at this time and let that be a new feature.

To get this "done":

- [x] Create CI Workflow to Release/Tag new releases with Artifactsin Github Releases.
- [x] Update `netdata/netdata` Installer to grab latest `netdata/kernel-collector` release and install it
- [x] Test

**Comment by thiagoftsm** [comment]
I would do the installation process in the following steps:

1 - To do download of the shared libraries and eBPF programs.
2 - Extract the content inside a directory ```tar -xf netdata_ebpf-5_4-glibc.tar.xz -C /tmp/eBPF_RANDOM_VALUE``
3 - Get the list of possible output directories to store the `libbpf_kernel.so` running: ```ldconfig -v 2>/dev/null | grep ':$' |sed -e 's/://' ```
4 - use one of the directories listed in the previous output, please, it is a good idea to get a directory inside `/usr/`
5 - copy `libbpf_kernel.so` to the directory elected in the previous command.
6 - create a symbolic link for `libbpf_kernel.so` inside the destination directory that finishes with `.0`: ``` ln -s `libbpf_kernel.so` `libbpf_kernel.so.0`
7 - move all the other files extracted to `/usr/libexec/netdata/plugins.d`

**Comment by prologic** [comment]
Implemented ☝️

**Comment by prologic** [comment]
Done with https://github.com/netdata/netdata/pull/8075 up
