### ISSUE TITLE
Unified library

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/kernel-collector#129]
After we merge the PR #127 , we can convert the whole structure build on top of kernel `5.4.20` for all kernels newer than `4.17.0`. To reach this goal it will be necessary to do the following steps:

- It is necessary to adjust the Docker files to rename eBPF programs and the file `libnetdata_ebpf.so` for a pattern easy to be identified.
- We will rename the final output used in the release for a name that also follows the pattern.
- We also need to adjust the files that calculate the checksum .
- We will remove all instructions used to compile any kernel different of 5.4.20, I will give a suggestion,  we also need to update for the kernel `5.4.32` that is the newest LTS kernel.

**Comment by thiagoftsm** [comment]
The second package that is necessary to build is a version that will support `4.15.x` and `4.16.x`, for this new group my suggestion is use the eBPF program compiled on `4.16.18`.

**Comment by thiagoftsm** [comment]
The third package that we need to release is based in the kernel `4.14.171`, this group should cover all kernels between `4.11.x` and `4.14.x', but we only tested on `4.14` .

**Comment by thiagoftsm** [comment]
The fourth and last package that we will need to create is for CentOS 7.x and RH 7.x.

**Comment by thiagoftsm** [comment]
After to define the 4 packages that we need, I think that we can organize our CI to build them and we move in front all the necessary changes.

**Comment by prologic** [comment]
Sounds good ot me. Let me know when you're pieces are ready and I'll update the Packaging and CI workflows around you.

**Comment by thiagoftsm** [comment]
Today I will bring more two PRs with improvements with code and tomorrow we can do the changes on the CI.

Thank you!

**Comment by thiagoftsm** [comment]
@prologic I already created the PR #135 that does the first steps for we move in front and create the new packages we will install on user's machine, but we need to define yet the name that we will give for the packages considering that now they support multiple kernels now.

**Comment by prologic** [comment]
How about: `netdata-ebpf-<kernel_from>-<kernel_to>.tar.xz`.

Example(s):

- `netdata-ebpf-4_11-5_3.tar.xz`

**Comment by thiagoftsm** [comment]
> How about: `netdata-ebpf-<kernel_from>-<kernel_to>.tar.xz`.
> 
> Example(s):
> 
>     * `netdata-ebpf-4_11-5_3.tar.xz`

I liked, I will change the PRs to use these names, I will also change the eBPF programs to follow this pattern.
