### ISSUE TITLE
Package and Ship eBPF and Shared Libraries per Kernel

### ISSUE THREAD

**Issue by prologic** [netdata/kernel-collector#13]

**Comment by prologic** [comment]
With the tremendous work by all and especially @thiagoftsm we're actually pretty close to being able to ship these. We already ship them to Github Actions per build so these are testable as of now.

**Comment by thiagoftsm** [comment]
We could see today your C skills appearing, so you do not need to be so humble! ;)

**Comment by prologic** [comment]
This is "done".
