### ISSUE TITLE
Getting redhat kernel version from userspace

### ISSUE THREAD

**Issue by mfundul** [netdata/kernel-collector#137]
When we get the running kernel version from userspace we do this:
https://github.com/netdata/kernel-collector/blob/b127df0e4590e30411cc964f2e8dcbac77000353/user/process_user.c#L184

However, when we want to identify if it's a redhat kernel we just look for the `redhat-release` file:
https://github.com/netdata/kernel-collector/blob/b127df0e4590e30411cc964f2e8dcbac77000353/user/process_user.c#L215

The `redhat-release` file has no relation to the running kernel. The user may be running one of the various LTS kernels that are not redhat kernels, or may even be running a different redhat kernel than the latest kernel the file `redhat-release` points to.

Proposal:
What we should be doing instead is:
- Look for `.el6.`, `.el7.`, `.el8.` in the kernel version string to identify if it's a redhat kernel.
- Map the redhat kernel versions to their corresponding releases (https://access.redhat.com/articles/3078), e.g.:
  - RHEL 8.1 `4.18.0-147`
  - RHEL 8.2 `4.18.0-193`
  - RHEL 7.8 `3.10.0-1127`
  - RHEL 7.7 `3.10.0-1062`

etc.

**Comment by thiagoftsm** [comment]
Thank you for the suggestion, I will fix this next sprint.

**Comment by thiagoftsm** [comment]
This was already merged.
