### ISSUE TITLE
Add gcc build environment and build variants

### ISSUE THREAD

**Issue by prologic** [netdata/kernel-collector#15]
```sh
/kernel-collector # find . -type f -name '*.so'
./library/libbpf.so
./user/libnetdata_ebpf.so
/kernel-collector # ldd ./library/libbpf.so
	/lib/ld-musl-x86_64.so.1 (0x7f20d764c000)
Error loading shared library libelf.so.0: No such file or directory (needed by ./library/libbpf.so)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f20d764c000)
```

**Comment by thiagoftsm** [comment]
I am also assigning myself here case we need to do a dynamic load .

**Comment by prologic** [comment]
I _think_ we're reaching a decision in #ebpf where:

- We will just link against glibc and musl
- Have glibc and musl variants

So the matrix of supported assets will look something like this:

- Kernel 5.4 + GLIBC + "out stuff"
- Kernel 5.4 + musl + "out stuff"
- ... _etc_ ...

**Comment by prologic** [comment]
@Ferroin @thiagoftsm So as previously discussed on Slack; we will have two build environments that will give us the capability of building and linking against glibc as well as musl. So on that note I will re-title this issue and re-label as "Add gcc build environment". Sound good?

**Comment by thiagoftsm** [comment]
> @Ferroin @thiagoftsm So as previously discussed on Slack; we will have two build environments that will give us the capability of building and linking against glibc as well as musl. So on that note I will re-title this issue and re-label as "Add gcc build environment". Sound good?

For me it is ok, go in front with your idea! :)

**Comment by prologic** [comment]
> For me it is ok, go in front with your idea! :)

Well we need it anyway :) And I'll base it very similarly to what we have here already; but I'll obviously have to abstract out the "prepare build dependencies" part.
