### ISSUE TITLE
Fix static builds for 4.16.18 4.18.0 and 3.10.0

### ISSUE THREAD

**Issue by prologic** [netdata/kernel-collector#153]
ssia

- [4.18.18](https://github.com/netdata/kernel-collector/pull/150/checks?check_run_id=716706580)
- [4.18.0](https://github.com/netdata/kernel-collector/pull/150/checks?check_run_id=716706610)
- [3.10.0](https://github.com/netdata/kernel-collector/pull/150/checks?check_run_id=716706691)

cc @thiagoftsm

**Comment by thiagoftsm** [comment]
When using `static` on `4.16.18` we were trying to use `alpine` instead `ubuntu`:

```

Run if [ 4.16.18 = "4.18.0" ]; then
  if [ 4.16.18 = "4.18.0" ]; then
    os=centos8
  elif [ 4.16.18 = "3.10.0" ]; then
    os=centos7
  else
    os=generic
  fi
  ./build.sh 4.16.18 static "${os}"
  shell: /bin/bash -e {0}
Sending build context to Docker daemon  2.841MB

Step 1/15 : FROM alpine:3.11 AS build
```

The expected is:

```

3m 18s
  shell: /bin/bash -e {0}
Run if [ 4.16.18 = "4.18.0" ]; then
  if [ 4.16.18 = "4.18.0" ]; then
    os=centos8
  elif [ 4.16.18 = "3.10.0" ]; then
    os=centos7
  else
    os=generic
  fi
  ./build.sh 4.16.18 glibc "${os}"
  shell: /bin/bash -e {0}
Sending build context to Docker daemon  2.841MB

Step 1/18 : FROM ubuntu:20.04 AS build
```

**Comment by thiagoftsm** [comment]
On `4.18.0` we are missing headers and for `3.10` there is a warning saying that compiler does not have an option. For these last two, we also did not have the docker files, but I am bringing them with #163.

**Comment by thiagoftsm** [comment]
This is not more necessary with the newest structure.
