### ISSUE TITLE
Software to test

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/kernel-collector#30]
We need a software that will load the eBPF software in the environment and verify that everything will work there.

**Comment by prologic** [comment]
> We need a software that will load the eBPF software in the environment and verify that everything will work there.

Just the CI environment I _think_. Its not enough that we can build; but we should also verify we can load/run what we've built. Full e2e testing should be covered by #12

**Comment by thiagoftsm** [comment]
The software present in the PR loads the shared libraries and the eBPF program , case everything goes fine it returns 0, and case there are problems, it will return a positive integer.
I think you wanna add a call for the software inside your docker files.

**Comment by prologic** [comment]
> I think you wanna add a call for the software inside your docker files.

Yes! Precisely :)
