### ISSUE TITLE
Library destination and symbolic link (installer)

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/kernel-collector#45]
While I was installing on other Linux distributions, I detected that we will need to take care with the following possible problems:

1 - Some distrubuitions(I detected this on Ubuntu), do not use default directories like `/usr/lib64/`or `/usr/lib` to store the libraries, and after to install the libraries in their LIB directories, it is also necessary to run `ldconfig`.
2 - Considering that the final destination will change in various distributions, it will be necessary to create the symbolic link `libnetdata_kernel.so.0`, after to copy the final destination.

**Comment by prologic** [comment]
Is it possible to avoid messing around with the user's systems too much and put the libraries in a known location; say `/usr/libexec/netdata/...` and just use `LD_LIBRARY_PATH` on our side?

**Comment by thiagoftsm** [comment]
I think so, my suggestion was in the direction to avoid to touch LD_LIBRARY_PATH, because some distributions do not have it explicitly , instead they use `/etc/ld.so.conf`, but case we can change this to be sure that the default user that runs Netdata will always have it, I do not see any problem.

**Comment by prologic** [comment]
Yeah I'm a bit indifferent here myself.

We can either:

- Put the libraries in `/usr/lib` or `/usr/lib64`

or:

- Put them in `/usr/libexec/netdata/lib`
- Ensure `LD_LIBRARY_PATH` is set correct in NetData startup scripts

**Comment by thiagoftsm** [comment]
Ubuntu uses another different directory, it is something called `/lib/x86...`, so probably it will be easier for us the second option.

**Comment by thiagoftsm** [comment]
When you begin to work on this, please, take a look on https://github.com/netdata/kernel-collector/issues/14 to identify the kernel version compatibility.

**Comment by prologic** [comment]
> When you begin to work on this, please, take a look on #14 to identify the kernel version compatibility.

We're going to have to encode that knowledge in our tools I suppose. A mapping of "netdata_" package against a list of compatible Kernels?

**Comment by thiagoftsm** [comment]
> We're going to have to encode that knowledge in our tools I suppose. A mapping of "netdata_" package against a list of compatible Kernels?

Yes, it is impossible to run an eBPF program compiled on 5.4.x on a distribution running 4.14.x and vice versa.

**Comment by prologic** [comment]
This was fixed by netdata/netdata@420d972c
