### ISSUE TITLE
Logic inside `library/Makefile` does not work on Ubuntu 18.04

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/kernel-collector#69]
The distribution Ubuntu has a different way to name the kernel version, instead to use only X.Y.Z, it names the kernel with `X.Y.Z-W-TEXT`, for example, on Ubuntu 18.04 we have `4.15.0-88-generic`, this breaks completely the following logic that we have inside `library/Makefile`:

```
VER_MAJOR=$(shell uname -r | cut -d. -f1)
VER_MINOR=$(shell uname -r | cut -d. -f2)
VER_PATCH=$(shell uname -r | cut -d. -f3)

CURRENT_KERNEL=$(shell echo $(VER_MAJOR)\*65536 + $(VER_MINOR)\*256 + $(VER_PATCH) |bc)
```

We need to find a way to fix this for we select the correct libbpf directory.

**Comment by prologic** [comment]
@thiagoftsm I need some clarification here... We don't currently build eBPF packages in [kernel-collector](https://github.com/netdata/kernel-collector) against an Ubuntu 18.04 build env. So can you help me understand why this is a problem? Do we need to because of some special 4.15 kernel we need to have published packages for?

**Comment by thiagoftsm** [comment]
I cited Ubuntu, because this was the place I detected the problem, but any other distribution that decides to use a kernel version different of `X.Y.Z` will create problems for us, so we need to find a way to catch only the number that we really care to define the variables.
The current Ubuntu kernel version does not allows to compile the kernel using the current libbpf version, we are compiling against the first libbpf, but the correct is the latest.

**Comment by prologic** [comment]
So... Let me be clear here; Are we able to fully support Ubuntu 18.04 with their strange 4.15.x-y-blah kernels by simply adding a 4.15 build variants to our already existing CI setup? Or are you saying we specifically need to build against an Ubuntu 18.04 system (_I hope not!_)

**Comment by thiagoftsm** [comment]
We need to divide this in steps:
-   Firstly we need to be able to do the correct identification of the kernel;
-   We will need to compile the kernel 4.15 in our CI

I believe after these two steps, we will be able to do, because when I compiled on Ubuntu the eBPF program everything worked fine, and I hope that compiling the kernel 4.15.18 I can install the files on Ubuntu and everything works.
For while I am keeping my believe that Red Had families will be the unique that will need a specific compilation, I do not believe we will need to do this with Ubuntu.

**Comment by prologic** [comment]
Okay; putting up another build variant for `4.15.18` should be trivial. Just add it to the CI and push a new PR. Have you tried this already? Are there any problems with the build? We can then test the resulting artefact.

**Comment by thiagoftsm** [comment]
I did not try after to get few errors on local docker.
The error happens when we are compiling the kernel source code thanks some options we use as you can see: 

```
./arch/x86/include/asm/atomic.h:192:1: error: '-mindirect-branch' and '-fcf-protection' are not compatible
```
