### ISSUE TITLE
Missing Kernel 4.15

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/kernel-collector#70]
We cannot run the module compiled on kernel 4.19 when we are using 4.15, we also cannot use the module compiled for 4.14 there, so we will need to add to our list of compiled kernel this version.
It will also be necessary  to change the `netdata-installer` that tests the kernel version before to do download of the correct file.

**Comment by thiagoftsm** [comment]
An additional information, when I executed the following command:

```
docker build --build-arg KERNEL_VERSION=4.15.18 -f Dockerfile.glibc -t kernel-collector:glibc ./
```

I got errors and it could not go until the end, but when I installed the package `linux-source` on ubuntu distribution, I could do the necessary steps and compile the eBPF  programs.

**Comment by prologic** [comment]
Oh I see #69 and #70 are related I _think_ I just answered my own question!

**Comment by prologic** [comment]
> It will also be necessary to change the netdata-installer that tests the kernel version before to do download of the correct file

There is no way we can do this now before the `v1.20.0` release; it will have to come as a nightly or patch release.

**Comment by prologic** [comment]
> I got errors and it could not go until the end, but when I installed the package linux-source on ubuntu distribution, I could do the necessary steps and compile the eBPF programs.

I will look into this; having to install the Distro kernelheaders / kernel-source should be 100% unnecessary the way I've setup the build environments.

**Comment by thiagoftsm** [comment]
I was thinking to do exactly what you said, right now the collector is not enabled by default, so we can postpone this for while, but for the next versions eBPF will continue growing, so we will need to extend kernel support and tests against more kernels.

**Comment by prologic** [comment]
Completely agree. This also places #12  higher up on the list of things to do.
