### ISSUE TITLE
Kernels that do not require gcc adjusts

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/kernel-collector#85]
We need to bring support for the following kernel versions that compiles without any kind of adjusts in the flags:

- 4.20.17 ( Gentoo)
- ~4.18.20 ( Fedora and Ubuntu)~
- 4.19.6 ( Debian 10)
- 4.19.105 (Debian 10.2 )

**Comment by prologic** [comment]
Updated desc :) But will leave on your plate! Just ping me if you need any help of course!
