### ISSUE TITLE
Two branches for kernel-collector

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/kernel-collector#88]
Netdata 1.20 was released with a code base and we are changing the code improving the collectors, but some improvements like https://github.com/netdata/kernel-collector/pull/83 are not compatible with the first release of Netdata with support to eBPF. 
@prologic is it possible, at least for the first releases, we have two branches? The first would keep freeze the same code basis we used to generate the stable 1.20, and the next will have the code for 1.21

**Comment by prologic** [comment]
It is technically possible of course; But I'd rather we find a way not to have to maintain multiple "release branches" if we can.

**Comment by thiagoftsm** [comment]
Considering that we are working to bring for `netdata-installer.sh` static versions, we do not need another branch, so I am closing this issue, case you do not agree, be free reopen.
