### ISSUE TITLE
Missing kernel options

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/kernel-collector#89]
We need to bring the missing options for the our script `./tools/check-kernel.config.sh`, we are dealing only with kprobe events, but it is necessary to consider the mount points among other possible options.

**Comment by thiagoftsm** [comment]
The following options are missing:

- CONFIG_BPF=y
- CONFIG_BPF_SYSCALL=y
- CONFIG_BPF_JIT=y
- CONFIG_FTRACE=y

**Comment by prologic** [comment]
Overlaps with #101 and implemented by #102

**Comment by hamzash9500** [comment]
guys, I get the following message during install netdata , can you help me,i need to enable ebpf plugin.
 Missing Kernel Config: KPROBES
 FAILED 

Thanks in advance

**Comment by thiagoftsm** [comment]
Hi @hamzash9500 ,

I have some doubts to give you a proper help:

1 - what is your Linux distribution? 
2 - what kernel is it running?

Best regards!

**Comment by hamzash9500** [comment]
linux distribution : Ubuntu 18.04.5 LTS
kernel : 4.9.140-tegra

**Comment by thiagoftsm** [comment]
Netdata is using an [API](https://elixir.bootlin.com/linux/v4.11.12/source/tools/lib/bpf/bpf.h) to communicate with the  kernel that was released with the kernel version 4.11. Unfortunately kernels older than this are not supported by Netdata at this moment. We apologize for this!

**Comment by hamzash9500** [comment]
but my kernal version is 4.9 ?!!

**Comment by hamzash9500** [comment]
ok thank you for `effort,`
is there any method i can use it to monitor bandwidth per process without using ebpf .

**I hope there is a way because I desperately need to achieve this duty.**

Thanks in advance

**Comment by thiagoftsm** [comment]
Hi @hamzash9500 ,

Unfortunately it is not possible, this feature was created with `ebpf.plugin`, because it is necessary to monitor sockets inside the kernel to bring it.

Best regards!

**Comment by hamzash9500** [comment]
Thank you for you effort.
