### ISSUE TITLE
Support kernels 4.11 and 4.13

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/kernel-collector#95]
It is necessary to map the distributions that used kernels between 4.11 and 4.13, and we need to bring support for these kernels.

**Comment by prologic** [comment]
Actually I'm not sure I agree here. cc @Ferroin . These kernels are probably too old for us to really care about because the Linux Distro versions they _might_ have been used on are long gone or already unsupported.

Do we have a list of which Distro versions use these Kernels? (_I had a look on DistroWatch last night and I could not find any that I thought would be relevant today..._)

**Comment by prologic** [comment]
Added to our Refinement board for discussion. Added @Ferroin as assignee

**Comment by prologic** [comment]
@cakrit Sorry to bug you on this one; but I can't make heads or tails of this GA UI :) Is there a way to download all of the raw data so I can slice and dice it myself with UNIX tools? :)

@Ferroin / @thiagoftsm It _does_ look like we have a significant no. of users on older Kerens -- even ones much older than what is listed in this issue (_which I could figure out a way to share a recent link_). -- OTOH though I _think_ (_not 100% certain_) that this is the result of a) Running old RHEL-based Amazon Linux instances (_prevumsbly in AWS via EC2_) and b) Docker Containers (Alpine) with varrying old Kernels ranging from 4.4 to 4.11

**Comment by thiagoftsm** [comment]
@prologic case nobody is using the kernels 4.11, 4.12 and 4.13 we do not look on it right now.
I am also working to create one common interfaces for these kernels, case the changes I am working on 4.14 is enough to solve this problem we can close this issue.

**Comment by cakrit** [comment]
I sent the export via Slack.

**Comment by prologic** [comment]
@thiagoftsm Did you see the export @cakrit provided? Both his export and my flimsy GA usage shows there are significant no. of users on these kernels.

**Comment by thiagoftsm** [comment]
I could not access the GA, but considering that we do not have many distributions using it and there was not any LTS  kernels between 4.11 and 4.13, let us close this `feature request` and  reopen it case we bring support to kernel `4.9`.
